# Generated by Django 3.2.5 on 2021-07-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_userlogin_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
